### ISSUE TITLE
MongoOutput stage failed after +- 8 hours

### ISSUE THREAD

**Issue by wzorgdrager** [codefeedr/codefeedr#133]
Exception:
```
com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:230)
	at com.mongodb.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:216)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:430)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:191)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Possible fixes: 
- https://stackoverflow.com/questions/39079876/mongosocketreadexception-prematurely-reached-end-of-stream-after-a-period-of-i
- https://stackoverflow.com/questions/33008514/what-is-the-solution-com-mongodb-mongosocketreadexception-and-com-mongodb-mon

**Comment by gousiosg** [comment]
How can it be that no write/read was done for 8 hours? In any case, you can probably use the keepAlive option when connecting. I hope that the Java/Scala driver has this.

**Comment by wzorgdrager** [comment]
There were writes.. I meant after successfully running the stage for 8 hours it crashed 'randomly'. In the stackoverflow they mentioned setting the `connectionIdleTime`.
